### ISSUE TITLE
Authenticate all requests

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-server#11]
- [ ] Vehicle CRUD is authenticated
- [ ] Commodity CRUD is authenticated
- [ ] Cluster CRUD is authenticated
- [ ] Vehicle websockets is authenticated
- [ ] Commodity websockets is authenticated
- [ ] Cluster websockets is authenticated

**Comment by aj-michael** [comment]
This has been punted to Sprint 4 (or possibly later).

**Comment by danhanson** [comment]
this issue is outdated since we are authenticating the connection itself, look here #95
