### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-server#2]
- [x] HTTP API documentation.
- [x] Websocket API documentation.

**Comment by grovecj** [comment]
[API Documentation](http://docs.pathfinder1.apiary.io/#)  

The documentation is consistent with the [sprint 0 pull request](https://github.com/CSSE497/pathfinder-server/pull/1)

**Comment by aj-michael** [comment]
Web socket API documentation is available here: https://github.com/CSSE497/pathfinder/wiki/WebSocket-API

**Comment by grovecj** [comment]
Total hours worked: 
Carter (restful api) - 1.5 hrs
Dan (websockets) - 1.5 hrs
