### ISSUE TITLE
Routes do not start at the current vehicle location

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-server#21]
Currently, the first action in the route list is the first pickup. It should be the current location of the vehicle.

**Comment by danhanson** [comment]
If we add a start action, should there also be an end action?

**Comment by aj-michael** [comment]
I don't think so, because we do not know in advance what the vehicle will do after it drops off its last commodity.

**Comment by danhanson** [comment]
I added a new Start action that has the position of the vehicle. Would we also want to store the vehicle id in it?
