### ISSUE TITLE
Working clusters

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-server#27]
- [x] Add cluster id to web socket create message for vehicle
- [x] Add cluster id to web socket create message for commodity
- [x] Fix cluster web socket create message to not through Postgres Syntax errors
- [ ] Make routes specific to clusters

**Comment by danhanson** [comment]
I mostly got clusters to work, you need to provide the cluster id to create vehicles and commodities, you can read clusters and view the elements in them, when you create a new vehicle or commodity, it is added to the specified cluster

**Comment by aj-michael** [comment]
Postgres syntax errors were fixed in #35

**Comment by aj-michael** [comment]
@danhanson, what is the status of the last checkbox?

If it is incomplete, please cross it out here and move it to a new issue for Sprint 5 so that we can close this issue.

**Comment by aj-michael** [comment]
Seeing as @danhanson never responded, I am closing this issue since Sprint 4 ended a week ago.
