### ISSUE TITLE
Pulls for Commodities and Clusters

### ISSUE THREAD

**Issue by danhanson** [CSSE497/pathfinder-server#28]
Users should be able to subscribe to notifications whenever commodities are added or removed as well as support cluster level subscription
- [x] Subscribe to receive updated commodities by commodity id
- [x] Subscribe to receive updated vehicles by vehicle id
- [x] Subscribe to receive updated routes by vehicle id
- [x] Subscribe to receive updated routes by commodity id
- [x] Subscribe to receive updated routes by cluster id

**Comment by danhanson** [comment]
I did not finish this in sprint

**Comment by danhanson** [comment]
I am moving it to sprint 5

**Comment by danhanson** [comment]
I am adding vehicle notifications to this feature

**Comment by danhanson** [comment]
Added subscriptions to routes requirements

**Comment by aj-michael** [comment]
@danhanson What is the status of this? I believe you have opened a pull request for at least some of this.

**Comment by danhanson** [comment]
I need to fix the tests

**Comment by danhanson** [comment]
Tests have been fixed
