### ISSUE TITLE
Improved Routing using Google Maps API and Websockets

### ISSUE THREAD

**Issue by danhanson** [CSSE497/pathfinder-server#29]
Implement cluster level routing that uses websocket notifications that uses the google maps API to calculate routes.
- [x] Calculates the shortest routes using Google Maps API
- [x] Recalculates whenever a vehicle or commodity is updated or added
- [x] Allows subscriptions to route updates by vehicle and by commodity
- [x] Considers the capacities of the vehicles as well as the weights of the commodities

**Comment by aj-michael** [comment]
Checkboxes marked to reflect status at the end of Q1.

**Comment by danhanson** [comment]
Closed this is out dated
