### ISSUE TITLE
Vehicles should have names that identify the drivers

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-server#38]
On the client side, I'd like to be able to display the driver's name and either a picture of the driver or a picture or their vehicle.

Thoughts? @grovecj @danhanson @robinsdm

**Comment by grovecj** [comment]
That seems like a common enough use case to justify implementing

**Comment by aj-michael** [comment]
@danhanson @robinsdm Mike mentioned that we should allow developers to store metadata in the form of Strings, Booleans or Numbers.

**Comment by danhanson** [comment]
We are using a metadata property that developers can use.
