### ISSUE TITLE
Webservice: Implement sockets

### ISSUE THREAD

**Issue by grovecj** [CSSE497/pathfinder-server#5]
Implement existing RESTful calls with sockets
- [x] API calls for each of the models
  - [X] Vehicles
  - [x] Commodities
  - [x] Clusters
- [x] Subscribing to push notifications
  - [x] Vehicles
  - ~~Commodities.~~
  - ~~Clusters.~~

See #24

**Comment by danhanson** [comment]
made websocket api vehicles vehicles #5

**Comment by danhanson** [comment]
we are now working on making commodities and clusters work with it #5

**Comment by aj-michael** [comment]
CRUD API was implemented in #14

**Comment by aj-michael** [comment]
@danhanson is working on subscribing/pushing.

**Comment by danhanson** [comment]
So now we can subscribe to routes by vehicle when a vehicle is created #24

**Comment by aj-michael** [comment]
I personally spent 15 hours on this this week.

**Comment by danhanson** [comment]
I worked 25 hours but I think the additional work would take another 10 hours

**Comment by danhanson** [comment]
Pushing for clusters and commodities have been moved to a new issue #28
