### ISSUE TITLE
Switch to only using path names

### ISSUE THREAD

**Issue by robinsdm** [CSSE497/pathfinder-server#59]
Transports, Commodities, and Clusters should all use paths for there unique key. Note, that the names must be unique across all the Pathfinder objects and the full names must be returned with requests. With this the id field may be removed.

**Comment by robinsdm** [comment]
Also, if this gets changed the app id will either have to be sent with every request or remembered across requests, because paths only need to be unique across one application. Lastly, parent ids will no longer be necessary, because you should be able to get them from the path.

**Comment by robinsdm** [comment]
Also, the default cluster's path name cannot be "/".  It makes very little since, if "/grand/parent/child"'s parent is "/grand/parent" and "/grand"'s parent is "/". The default cluster path should be something like "/default", to make it consistent.

**Comment by danhanson** [comment]
well transports and commodities have a cluster path and id for now I don't think we will change this any time soon unless we run into problems or something
