### ISSUE TITLE
Easier to parse websocket messages

### ISSUE THREAD

**Issue by robinsdm** [CSSE497/pathfinder-server#60]
In line with #59 the websocket CRUD messages should be updated to something easier to parse. The message should be a JSON object with the message type as part of the body. So there can less if statements to get the message to the right place. Also, the message should include its recipient path with the message type in the body. This is to make it unambiguous where the message should be sent to. Here is an example.

Old style

```
{
   "created":{
     "model":"Vehicle",
     "value":{
        "id":20,
        "latitude":0.123,
        "longitude":0.456,
        "status":"Online",
        "metadata":{"capacity":4}
     }
   }
}
```

New style

```
{
   "type":"created",
   "path":"/team/tigers/tiny/tim",
   "value":{
      "model":"Transport"
      "path":"/team/tigers/tiny/tim",
      "latitude":0.123,
      "longitude":0.456,
      "status":"Online",
      "metadata":{"capacity":4}
   }
}
```

Note the top "path" is the path to the object that is supposed to receive the message. The nested "path" is the path to the object that changed. For the most part they should be the same, but could be different when subscribing to clusters. The first "path" would be the cluster's path. The nested "path" would be the path to the transport or commodity that was changed.

**Comment by danhanson** [comment]
this issue is redundant since all changes accept for the path have been made and that is covered in #59.
