### ISSUE TITLE
Socket error messages should include the path of the request

### ISSUE THREAD

**Issue by robinsdm** [CSSE497/pathfinder-server#62]
Currently error message from socket requests cannot be routed to the object that created the error. To fix this the error message should include the path of the object that created the message, so the error message can be given to the offending object. It should look something like:

```
{
   "type":"error",
   "path":"blah/da/de/da",
   "value": {
      "reason":"Already exists"
   }
}
```

**Comment by danhanson** [comment]
We might do this later but will ignore it for now
