### ISSUE TITLE
Path-finder server should use google maps api and routing server to receive routes

### ISSUE THREAD

**Issue by danhanson** [CSSE497/pathfinder-server#66]
We will be using a routing server implemented in julia to calculate optimal routes based on data received from google maps api
- [x] Receive distances and time using google maps API
- [x] Send request to julia server containing commodity and transport data from the database and data from the google maps api
- [x] Uses the response to notify route subscribers of route changes
- [ ] The code written for these tasks is tested

**Comment by danhanson** [comment]
It all works

**Comment by danhanson** [comment]
I should probably write a test or two

**Comment by aj-michael** [comment]
Nice work! :sheep:
