### ISSUE TITLE
Subscribe and Unsubscribe messages need the cluster path

### ISSUE THREAD

**Issue by robinsdm** [CSSE497/pathfinder-server#96]
- [ ] The subscribe message needs to include the model type (cluster, commodity, transport).
- [ ] The subscribe message needs to include the clusterId for subscribing to specific commodities and transports.
- [ ] The unsubscribe message needs to include the clusterId for unsubscribing to specific commodities and transports.

Also, it would be nice if the cluster subscribe messages updated you on both commodity and transport changes by default.

**Comment by aj-michael** [comment]
i don't think this should go in sprint 11, it seems very low priority because all of those messages already work, just maybe not how you want them to. It's spring quarter, if we don't start moving faster, we're not going to finish.

**Comment by danhanson** [comment]
I will ignore this for now since the unsubscribed messages are not really used
